name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install python3-pip -y && pip3 install flask
    - name: Deploy app
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -i /Users/mabdurrafey/Desktop/PL/KeyPair.pem ubuntu@ec2-52-207-71-84.compute-1.amazonaws.com "cd /home/ubuntu/CICD_Flask && nohup python3 app.py &"
