name: Deploy to EBS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      EB_APP_NAME: myflask
      EB_ENV_NAME: Myflask-env
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install python3-pip -y && pip3 install -r requirements.txt && pip3 install awsebcli
    - name: Deploy app
      run: |
        eb init --debug $EB_APP_NAME --platform python --region $AWS_REGION --quiet
        eb use $EB_ENV_NAME --quiet
        eb deploy --staged --timeout 10 --nohang
